name: Print Service Principal Roles

on:
  workflow_dispatch: # This triggers the workflow manually

jobs:
  print-roles:
    runs-on: ubuntu-latest
    steps:
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Fetch Service Principal Roles
        run: |
          # Fetch roles using Azure CLI and store the output in a variable
          roles=$(az role assignment list --all --query "[?principalId=='61934ba6-9b0b-4185-ba20-068d838db652']" --output table)
          

      - name: Print Service Principal Roles
        run: |
          echo "Roles for Service Principal:"
          # Print the fetched roles stored in the variable
          echo "$roles"
