name: Storage Account Provisioning

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  print-cache-directory:
    runs-on: ubuntu-latest
    steps:
      - name: Print Cache Directory
        run: |
          echo "Cache directory: ${{ runner.workspace }}/.cache"
          
  storage_provision:
    runs-on: ubuntu-latest
    needs: print-cache-directory
    outputs: 
      storage_provision_success: ${{ steps.create_resource_group.outputs.success }}    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Check if Resource Group exists
        id: check_rg
        run: |
          az group show --name StorageRG >/dev/null 2>&1 || { echo "::set-output name=exists::false"; exit 0; }
          echo "::set-output name=exists::true"

      - name: Check if Storage Account exists
        id: check_storage
        run: |
          az storage account show --name taskboardstorageybg --resource-group StorageRG >/dev/null 2>&1 || { echo "::set-output name=exists::false"; exit 0; }
          echo "::set-output name=exists::true"

      - name: Create Resource Group
        if: steps.check_rg.outputs.exists != 'true'
        run: |
          az group create --name StorageRG --location "North Europe"
            

      - name: Create Storage Account
        if: steps.check_storage.outputs.exists != 'true'
        run: |
          az storage account create --name taskboardstorageybg --resource-group StorageRG --location "North Europe" --sku Standard_LRS

      - name: Create Storage Container
        run: |
          az storage container create --name taskboardcontainer --account-name taskboardstorageybg
